### PR TITLE
Fix nested interconnect canonicalization and path traversal

### LINKED ISSUE #1195: `canonicalizeMemoryMapTree` does not work with nested interconnects
https://github.com/bittide/bittide-hardware/pull/1187 introduces a nested interconnect in the memorymap which then causes the `SwitchDemoTest` to fail due to `getPathAddress` not being able to resolve the address to `CaptureUgn0`. After investigation we found that `canonicalizeMemoryMapTree` was not able to canonicalize the `CaptureUgn` components in its memory map. All `CaptureUgn` components still have the `CaptureUgn` name instead of `CaptureUgnN`

### PR DESCRIPTION
**Pull request by lmbollen**
Fixes #1195
_What (what did you do)_
Change the implementation of `getPathAddress` to allow nested interconnects.  We add a utility to list the children of a given path (like the `ls` Shell command). This was implemented in order to allow for the user to determine the correct path to use in the case of finding a device in a memory map with nested interconnects.

_Why (context, issues, etc.)_
`getPathAddress` was broken for memorymaps with nested interconnects.

_Dear reviewer (anything you'd like the reviewer to pay close attention to?)_

_AI disclaimer (heads-up for more than inline autocomplete)_

# TODO
_~~Cross-out~~ any that do not apply_

- [x] Write (regression) test
- [ ] Update documentation, including `docs/`
- [x] Link to existing issue

### CODE REVIEW

File: bittide-instances/src/Bittide/Instances/Hitl/Utils/MemoryMap.hs [hunk 1]
```diff
@@ -75,48 +82,72 @@ getPathAddress ::
...
   a
-getPathAddress mm = traverseTree canonicalTree
+getPathAddress mm pathWithName =
+  let
+    errorMessage = error "Empty path given!"
+    (pfx, name) = fromMaybe errorMessage (unsnoc pathWithName)
+    children = listChildren mm pfx
+   in
+    case filter (\(_, childName) -> childName == name) children of
+      [] -> error [i|Prefix #{pfx} has no child #{name}|]
```
Comment (martijnbastiaan) [inline bittide-instances/src/Bittide/Instances/Hitl/Utils/MemoryMap.hs]: If you want to write this properly, things that are expected to go wrong (wrong user input) should return a `Left`. Things that are an internal error (i.e., the logic within this function would be wrong) can use `error`.

**Comment by martijnbastiaan** [comment]
@lmbollen I don't understand the test changes. Do they actually test nested interconnects now?
